apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/YOUR_NAMESPACE/dealership:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  type: NodePort
  selector:
    run: dealership
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
